### ISSUE TITLE
Week #4 Peer-to-Peer Code Review

### ISSUE THREAD

**Issue by rpire** [julie-ify/Portfolio-Mobile-version#13]
## Hello @julie-ify 🖐

Congratulations on your hard work! Your project is completely functional and looking really nice.

### Your code:

- Validates the form data correctly.
- Shows a proper error message when data is invalid.
- The error messages are shown near the.

### Requested Changes (OPTIONAL) ♻

- When the cursor is hovering over a `button` it could be made a `pointer`. That way users could be completely sure that your button is actually something clickable. What do you think about my suggestion? 🤓

Once again congratulations on your work until now. Cheers and Happy coding! 🚀

**Comment by julie-ify** [comment]
Thanks for the suggestion and I really appreciate it. I will quickly work on it.
Thanks, Teammates 💯
