### ISSUE TITLE
Desktop Version Review/Issues

### ISSUE THREAD

**Issue by HENRYKC24** [julie-ify/Portfolio-Mobile-version#5]
1. Skillset icons are not aligned. You could consider placing some items in the works section boxes in different containers.

2. Your navbar items are not bookmarked to different sections of your portfolio. For example, clicking the 'portfolio' link should navigate to the portfolio section of your app. Consider using the HTML bookmark for this implementation.

Nice job:+1: Juliana:clap:

**Comment by julie-ify** [comment]
I will quickly work on those issues. Thanks
